FROM cypress/included:9.5.0

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Fixes the strange permission issues GitHub Actions was having. 
RUN chmod -R 777 /app

# Override the entrypoint of the cypress/included image
ENTRYPOINT ["bash", "-c", "while !</dev/tcp/api/80; do sleep 1; done; npm run dev"]
