FROM cypress/included:9.3.1

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Override the entrypoint of the cypress/included image
ENTRYPOINT ["bash", "-c", "while !</dev/tcp/api/80; do sleep 1; done; npm run dev"]