version: "3.9"

services:
  cypress:
    entrypoint: bash -c 'until $$(curl --output /dev/null --silent --fail "http://ace2-ams:8080/login"); do sleep 1; done; xvfb-run cypress run --headed --browser chrome --config video=false,screenshotOnRunFailure=false'
