FROM node:16-alpine

WORKDIR /app

COPY package*.json .

RUN apk --no-cache add --virtual native-deps \
  g++ gcc libgcc libstdc++ linux-headers make python3 && \
  npm install --quiet node-gyp -g && \
  npm install --quiet && \
  apk del native-deps

COPY . .

EXPOSE 8080

CMD ["npm", "run", "serve"]