FROM public.ecr.aws/lambda/python:3.9

# copy entire repo over (this gets deleted by the final image to save space)
ADD . ace2

# install and test the ace2 library
RUN pip3 install ace2/lib/ace2
RUN pytest ace2/lib/ace2
