FROM ace2-base

# get path to module directory from build args
ARG module

# add the module
ADD $module module

# copy all lib files so setup script can install from them
ADD lib lib

# run module setup script if one exists
RUN if test -f "module/setup.sh"; then bash module/setup.sh; fi

# run module tests
RUN pytest module

# copy module to working dir
RUN cp module/module.py module.py

# cleanup install files
RUN rm -rf lib
RUN rm -rf module

# remove test packages to reduce image size
RUN pip3 uninstall -y pytest-datadir pytest

# set entrypoint to the module run function
CMD [ "module.run" ]
