FROM ace2-base

# get path to module directory from build args
ARG module

# run module setup
ADD lib lib
ADD $module/setup.sh setup.sh
RUN bash setup.sh
RUN rm -rf setup.sh lib

# run tests and install module
ADD $module module
RUN pytest -vv module/test.py
RUN cp module/module.py module.py
RUN rm -rf module

# uninstall testing tools
RUN pip3 uninstall -y pytest-datadir pytest

# set entrypoint to the module run function
CMD [ "module.run" ]
