FROM ace2-base

# get path to module directory from build args
ARG module

# run module setup script if one exists
RUN if test -f "ace2/$module/setup.sh"; then bash ace2/$module/setup.sh; fi

# run module tests
RUN pytest ace2/$module

# copy module to working dir
RUN cp ace2/$module/module.py module.py

# remove ace2 files to reduce image size
RUN rm -rf ace2

# remove test packages to reduce image size
RUN pip3 uninstall -y pytest-datadir pytest

# set entrypoint to the module run function
CMD [ "module.run" ]
