"""Add alert ownership time column

Revision ID: d882733db15d
Revises: 5f818dc4ffb9
Create Date: 2022-05-04 16:25:09.768092
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'd882733db15d'
down_revision = '5f818dc4ffb9'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('ownership_time', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_alert_ownership_time'), 'alert', ['ownership_time'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_ownership_time'), table_name='alert')
    op.drop_column('alert', 'ownership_time')
    # ### end Alembic commands ###